-- Eliminar tablas existentes
DROP TABLE RESIDENTE CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRACION_EXTERNA CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE VISITANTE CASCADE CONSTRAINTS;
DROP TABLE ADMIN_EMPLEADO_CONTRATADA CASCADE CONSTRAINTS;
DROP TABLE REGISTRO_VISITANTE_DEPTO CASCADE CONSTRAINTS;
DROP TABLE RESERVACION CASCADE CONSTRAINTS;
DROP TABLE ESTACIONAMIENTO CASCADE CONSTRAINTS;
DROP TABLE MULTA CASCADE CONSTRAINTS;
DROP TABLE ESPACIO_COMUN CASCADE CONSTRAINTS;
DROP TABLE ANUNCIO CASCADE CONSTRAINTS;
DROP TABLE BITACORA CASCADE CONSTRAINTS;
DROP TABLE ENCOMIENDA CASCADE CONSTRAINTS;

-- Creación de tablas ajustadas
--1
CREATE TABLE RESIDENTE(
    run_residente  VARCHAR2(10) CONSTRAINT PK_RESIDENTE PRIMARY KEY,
    dvrun VARCHAR2(1) NOT NULL,
    pnombre_residente VARCHAR2(50) NOT NULL, 
    snombre_residente VARCHAR2(50), 
    appaterno_residente VARCHAR2(50) NOT NULL, 
    apmaterno_residente VARCHAR2(50),
    fecha_nacimiento_residente DATE NOT NULL,
    fecha_contrato_residente DATE NOT NULL,
    correo_residente VARCHAR2(50),
    fono_contacto VARCHAR2(15) NOT NULL,
    tipo_residente  NUMBER(3) NOT NULL,
    comite NUMBER(1)
);

--2
CREATE TABLE ADMINISTRACION_EXTERNA(
    rut_admin  VARCHAR2(10) CONSTRAINT PK_ADMINISTRACION_EXTERNA PRIMARY KEY,
    nombre_admin VARCHAR2(50) NOT NULL,
    fecha_contrato_admin DATE NOT NULL,
    correo_admin VARCHAR2(50),
    fono_contacto_admin VARCHAR2(15) NOT NULL
);

--3
CREATE TABLE EMPLEADO(
    run_empleado  VARCHAR2(10) CONSTRAINT PK_EMPLEADO PRIMARY KEY,
    dvrun_empleado VARCHAR2(1) NOT NULL,
    pnombre_empleado VARCHAR2(50) NOT NULL, 
    snombre_empleado VARCHAR2(50), 
    appaterno_empleado VARCHAR2(50) NOT NULL, 
    apmaterno_empleado VARCHAR2(50),
    fecha_nacimiento_empleado DATE NOT NULL,
    fecha_contrato_empleado DATE NOT NULL,
    correo_empleado VARCHAR2(50),
    fono_contacto_empleado VARCHAR2(15) NOT NULL,
    tipo_empleado  NUMBER(3) NOT NULL
);

--4
CREATE TABLE VISITANTE(
    run_visitante  VARCHAR2(10) CONSTRAINT PK_VISITANTE PRIMARY KEY,
    dvrun_visitante VARCHAR2(1) NOT NULL,
    nombres_visitante VARCHAR2(80) NOT NULL, 
    apellido_visitante VARCHAR2(80) NOT NULL
);

--5
CREATE TABLE ADMIN_EMPLEADO_CONTRATADA(
    ID_ADMIN_EMPLEADO_CONTRATADA  VARCHAR2(10) CONSTRAINT PK_ADMIN_EMPLEADO_CONTRATADA PRIMARY KEY,
    run_empleado  VARCHAR2(10),
    rut_admin VARCHAR2(10),
    CONSTRAINT FK_ADMIN_EMPLEADO_CONTRATADA_EMPLEADO 
    FOREIGN KEY(run_empleado) 
    REFERENCES EMPLEADO(run_empleado),
    CONSTRAINT FK_ADMIN_EMPLEADO_CONTRATADA_ADMINISTRACION_EXTERNA FOREIGN KEY(rut_admin) 
    REFERENCES ADMINISTRACION_EXTERNA(rut_admin)
);

--6
CREATE TABLE REGISTRO_VISITANTE_DEPTO(
    ID_VISITANTE_DEPTO VARCHAR2(10) CONSTRAINT PK_VISITANTE_DEPTO PRIMARY KEY,
    run_visitante  VARCHAR2(10),
    run_residente  VARCHAR2(10),
    CONSTRAINT FK_VISITANTE_DEPTO_VISITA 
    FOREIGN KEY(run_visitante) 
    REFERENCES VISITANTE(run_visitante),
    CONSTRAINT FK_VISITANTE_DEPTO_RESIDENTE 
    FOREIGN KEY(run_residente) 
    REFERENCES RESIDENTE(run_residente)
);

--7
CREATE TABLE MULTA (
    ID_MULTA VARCHAR2(10) CONSTRAINT PK_MULTA PRIMARY KEY,
    DESCRIPCION_MULTA VARCHAR2(60),
    MONTO_MULTA NUMERIC(8),
    FECHA_HORA_MULTA DATE DEFAULT SYSDATE,
    run_residente  VARCHAR2(10),
    CONSTRAINT FK_MULTA_RESIDENTE
    FOREIGN KEY (RUN_RESIDENTE) 
    REFERENCES RESIDENTE(RUN_RESIDENTE)
);

--8
CREATE TABLE ESPACIO_COMUN (
    ID_EC VARCHAR2(10) CONSTRAINT PK_ESPACIO_COMUN PRIMARY KEY,
    NOMBRE_EC VARCHAR2(60),
    DESCRIPCION_EC VARCHAR2(60),
    CAPACIDAD_EC NUMERIC(10)
);

--9
CREATE TABLE ANUNCIO (
    ID_ASUNTO VARCHAR2(10) CONSTRAINT PK_ANUNCIO PRIMARY KEY,
    ASUNTO VARCHAR2(60),
    CONTENIDO_ASUNTO VARCHAR2(60),
    FECHA_HORA_ASUNTO DATE DEFAULT SYSDATE,
    RUN_EMPLEADO  VARCHAR2(10),
    CONSTRAINT FK_ANUNCIO_EMPLEADO
    FOREIGN KEY (RUN_EMPLEADO) 
    REFERENCES EMPLEADO(RUN_EMPLEADO)
);

--10
CREATE TABLE BITACORA(
    ID_BITACORA VARCHAR2(10) CONSTRAINT PK_BITACORA PRIMARY KEY,
    ASUNTO VARCHAR2(60),
    CONTENIDO VARCHAR2(200),
    FECHA_HORA DATE DEFAULT SYSDATE,
    RUN_EMPLEADO VARCHAR2(10),
    CONSTRAINT FK_BITACORA_EMPLEADO
    FOREIGN KEY (RUN_EMPLEADO) 
    REFERENCES EMPLEADO(RUN_EMPLEADO)
);

--11
CREATE TABLE RESERVACION (
    ID_RESERVACION VARCHAR2(10) CONSTRAINT PK_RESERVACION PRIMARY KEY,
    ESTADO_RESERVACION VARCHAR2(20),
    INICIO_FECHA_HORA_RESERVACION DATE DEFAULT SYSDATE,
    FIN_FECHA_HORA_RESERVACION DATE,
    RUN_RESIDENTE VARCHAR2(10),
    ID_EC VARCHAR2(10),
    CONSTRAINT FK_RESERVSACION_RESIDENTE FOREIGN KEY (RUN_RESIDENTE) 
    REFERENCES RESIDENTE(RUN_RESIDENTE),
    CONSTRAINT FK_RESERVSACION_ESPACIO_COMUN 
    FOREIGN KEY(ID_EC) 
    REFERENCES ESPACIO_COMUN(ID_EC)
);

--12
CREATE TABLE ESTACIONAMIENTO(
    ID_ESTACIONAMIENTO VARCHAR2(10) CONSTRAINT PK_ESTACIONAMIENTO PRIMARY KEY,
    tipo_auto NUMBER(1) NOT NULL,
    patente VARCHAR2(6),
    RUN_residente VARCHAR2(10),
    RUN_EMPLEADO VARCHAR2(10),
    RUN_visitante VARCHAR2(10),
    CONSTRAINT FK_ESTACIONAMIENTO_RESIDENTE
    FOREIGN KEY (RUN_RESIDENTE) 
    REFERENCES RESIDENTE(RUN_RESIDENTE),
    CONSTRAINT FK_ESTACIONAMIENTO_EMPLEADO
    FOREIGN KEY (RUN_EMPLEADO) 
    REFERENCES EMPLEADO(RUN_EMPLEADO),
    CONSTRAINT FK_ESTACIONAMIENTO_VISITANTE 
    FOREIGN KEY(run_visitante) 
    REFERENCES VISITANTE(run_visitante)
);

--13
CREATE TABLE ENCOMIENDA(
    ID_ENCOMIENDA VARCHAR2(10) CONSTRAINT PK_ENCOMIENDA PRIMARY KEY,
    ESTADO_ENCOMIENDA VARCHAR2(20),
    FECHA_HORA_ENCOMIENDA DATE,
    RUN_residente VARCHAR2(10),
    RUN_EMPLEADO VARCHAR2(10),
    CONSTRAINT FK_ENCOMIENDA_RESIDENTE
    FOREIGN KEY (RUN_RESIDENTE) 
    REFERENCES RESIDENTE(RUN_RESIDENTE),
    CONSTRAINT FK_ENCOMIENDA_EMPLEADO
    FOREIGN KEY (RUN_EMPLEADO) 
    REFERENCES EMPLEADO(RUN_EMPLEADO)
);

-- INSERT INTO "TABLA" VALUES();

COMMIT;
